# Generated by Django 3.1.7 on 2021-12-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_news_useraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
    ]
