# Generated by Django 3.2.9 on 2022-02-26 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('headlines', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
