# Generated by Django 3.2.9 on 2022-02-26 09:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Base', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('phone_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919800220022'. Upto 13 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('street', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='e.g. 14th street')])),
                ('city', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='e.g. Mumbai')])),
                ('state', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='e.g. Maharashtra')])),
                ('zip', models.IntegerField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='e.g. 400001')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
