# Generated by Django 3.2.9 on 2022-02-26 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zip',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919800220022'. Upto 13 digits allowed.", regex='^\\d{6}$')]),
        ),
    ]
